---
title: "Activité sur le fondements et les enjeux dans l'interprétation des outputs d'une méta-analyse"
author: |
  | **Mattia A. Fritz**
  | \small TECFA, Université de Genève
date: "`r format(Sys.time(), '%d/%m/%Y')`"
lang: fr
linestretch: 1.2
fontsize: 12pt
urlcolor: blue
output:
  pdf_document:
    toc: false
    toc_depth: 1
    number_sections: true
    latex_engine: xelatex
    extra_dependencies: ["flafter"]
    includes:
      in_header: "../settings/preamble.tex"
      before_body: "../settings/before-body.tex"
      #after_body: "doc-suffix.tex"
bibliography: ../bib/references.bib
csl: ../settings/apa.csl
abstract: "Cette activité propose"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
Sys.setlocale("LC_ALL", "French")
source(here::here("settings", "custom.R"))
```

# Test 
```{r}
n <- 200
data <- tibble(
  id = paste0("P", 1:n),
  age = sample(18:65, n, replace = TRUE),
  time = rnorm(n, 60, 10),
  condition = sample(c("Control", "Treatment", "Alternative"), n, replace = TRUE)
)

data |> 
  custom_table(caption_text = "What happens in here?")
```


# Another test
```{r}
#| fig.cap = "Test"
ggplot(data, aes(x = condition, y = time, color = condition)) +
  geom_jitter(alpha = 0.4) +
  stat_summary(fun.data = mean_cl_normal, geom = "errorbar", aes(group = condition, color = condition), width = 0.4) +
  stat_summary(fun = mean, geom = "point", aes(group = condition, color = condition), size = 3, shape = 15) +
  theme(
    legend.position = "none"
  ) +
  NULL
```

